version: "3.8"

services:
    backend: 
        container_name: backend
        build: ./backend
        environment:
            REDIS_HOST: redis
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
        depends_on:
            - redis
            - postgres
        ports: 
            - 8080:8080
            
    frontend:
        container_name: frontend
        build: ./frontend
        depends_on:
            - backend
        ports:
            - 5000:5000

    redis:
        container_name: redis
        image: redis
        restart: unless-stopped
        volumes:
            - ./redis_data:/data

    postgres:
        container_name: postgres
        image: postgres
        environment:
            PGDATA: /data
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
        volumes:
            - ./pg_data:/data