version: "3.8"

services:
    backend:
        image: backend
        container_name: backend
        build: ./backend
        environment:
            REDIS_HOST: redis
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
        depends_on:
            - redis
            - postgres
        ports:
            - "8080:8080"
            
    frontend:
        image: frontend
        container_name: frontend
        build: ./frontend
        ports:
            - "5000:5000"

    redis:
        image: redis
        container_name: redis
        restart: unless-stopped
        volumes:
            - ./redis_data:/data

    postgres:
        image: postgres
        container_name: postgres
        environment:
            PGDATA: /data
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
        volumes:
            - ./pg_data:/data

    web:
        image: nginx
        container_name: nginx_web
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"